name: Show Requirements File

on: [push]

jobs:
  display-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Show content of requirements.txt
        run: cat requirements.txt
